from generator.generator import Generator
from flask import Flask
from flask import request

app = Flask(__name__)


@app.route('/generate', methods=['POST'])
def generate():
    """
    Generate a new outfit.
    :return json outfit: An outfit generated by the MAB algorithm.
    e.g: {"articles":[{"look": "cosy", "category": "shoes", "articleId": "1"},
		             {"look": "cosy", "category": "trousers","articleId": "4"},
		             {"look": "cosy", "category": "tops", "articleId": "7"}]}
    """
    return Generator().generate(request.json)
