from generator.generator import Generator
from flask import Flask
from flask import request

app = Flask(__name__)


@app.route('/generate', methods=['POST'])
def generate():
    """
    Generate a new outfit.
    :return json outfit: An outfit generated by the MAB algorithm.
    """
    return Generator().generate(request.json)
